# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Darner-dan-uh' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Darner-dan-uh
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire', '~> 5.2'
pod "RxAnimated"
pod 'RxAlamofire'
pod 'RealmSwift'


end
